#!/usr/bin/env node

const Mbr=require("./Mbr.js");
const path=require("path");

if (process.argv.length!=3) {
	console.log("Usage: mbr <settingsfile>")
	process.exit();
}

let mbr=new Mbr(path.resolve(process.argv[2]));
mbr.run();
